[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["singlethread"]
singlethread = []
multithread = []

[dependencies]
anyhow.workspace = true
day1.workspace = true
day2.workspace = true
day3.workspace = true
clap = { version = "4.4.10", features = ["derive"] }
