[workspace]
resolver = "2"

members = ["bin", "day1", "day2", "day3"]

[workspace.dependencies]
anyhow = "1.0.71"
rayon = "1.8.0"

[workspace.dependencies.day1]
path = "day1"

[workspace.dependencies.day2]
path = "day2"

[workspace.dependencies.day3]
path = "day3"
